### ISSUE TITLE
Firebase failed upload

### ISSUE THREAD

**Issue by tenhishadow** [fastlane/fastlane-plugin-firebase_app_distribution#29] opened 2019-12-23 17:37 UTC
I got an error about uploading to Firebase:

```
 💥   | firebase_app_distribution                        | 40          |
+------+--------------------------------------------------+-------------+

ERROR [2019-12-23 15:53:46.98]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Shell command exited with exit status 1 instead of 0.
]0;Firebase CLIi  getting app details...
i  uploading distribution...

Error: failed to upload distribution. it took longer than expected to process your binary, please try again

URL: https://api.github.com/search/issues?q=Shell%20command%20exited%20with%20exit%20status%201%20instead%20of%200.%0A%1B%5D0%3BFirebase%20CLI%07%1B%5B1m%1B%5B36mi%20%1B%5B39m%1B%5B22m%20getting%20app%20details...%0A%1B%5B1m%1B%5B36mi%20%1B%5B39m%1B%5B22m%20uploading%20distribution...%0A%0A%1B%5B1m%1B%5B31mError%3A%1B%5B39m%1B%5B22m%20failed%20to%20upload%20distribution.%20it%20took%20longer%20than%20expected%20to%20process%20your%20binary%2C%20please%20try%20again%0A+repo:fastlane/fastlane
ERROR [2019-12-23 15:53:47.02]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
bundler: failed to load command: fastlane (/home/circleci/repo/vendor/bundle/ruby/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Shell command exited with exit status 1 instead of 0.
]0;Firebase CLIi  getting app details...
i  uploading distribution...

Error: failed to upload distribution. it took longer than expected to process your binary, please try again
```
This issue is in CircleCI when I do parallel distribution for bulk of envs. Is it possible to change timeout or catch this error with try again e.g. for 2 or 3 times?
Or maybe it's an interaction limit in Firebase?

**Comment by kevinkokomani** [comment] 2019-12-23 18:05
Hi tenhishadow, how large is the distribution you're trying to upload? There should be a 900 MB upload limit that might be affecting you here.

**Comment by tenhishadow** [comment] 2019-12-23 18:11
Oh, no.
It's just 57M

```
 tenhi@nlb08  ~  du -h app-arm64-v8a-staging.apk                                                                                                    ✔  2  21:08:19
57M     app-arm64-v8a-staging.apk
```

But I do parallel execution for 2 ios and 2 android. 
![workflow](https://user-images.githubusercontent.com/24500345/71373561-b2b33f80-25c8-11ea-9d91-7282d9c67bcf.png)

And as you can see, another build has been distributed correctly.
Here it is just something like a slow processing or smth else.

**Comment by tenhishadow** [comment] 2019-12-25 01:18
@kevinkokomani any ideas?

**Comment by kevinkokomani** [comment] 2020-01-07 20:30
Hey, sorry for the delay. 

I haven't heard specifically of an issue with parallel distribution, but that could be an avenue to look into. Does uploading builds work consistently if you're not distributing in parallel? That might be worth doing some testing with.

You're also using CircleCI - is this a locally hosted Circle instance or hosted on the cloud?

We also have seen transient issues where uploading distributions can fail occasionally when uploading from a place far away from our North American servers. Do the upload failures happen consistently overall, or have you noticed it working as intended at least some of the time?

**Comment by tonybaroneee** [comment] 2020-11-12 16:06
Closing this issue as we have since improved binary upload speeds, so timeouts should be less likely to happen now.

**Closed** 2020-11-12 16:06 UTC
